# Generated by Django 4.1.12 on 2023-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketreservation",
            name="to_date",
            field=models.DateField(blank=True),
        ),
    ]
